# 1. Where is the database? (It's in the p2p_db we made)
spring.datasource.url=jdbc:postgresql://localhost:5432/p2p_db
spring.datasource.username=postgres
spring.datasource.password=major2@123

# 2. How should Java talk to it?
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. Security Secret (We will use this for the locks later)
app.jwt.secret=MySuperSecretKeyForP2PProject2026
app.jwt.expiration-ms=86400000
# Email Configuration - Use your real Gmail and 16-letter App Password
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=p2p.exchangeresource@gmail.com
spring.mail.password=ptnz epqd ffct nsfu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true